enum RestApiRequestType
{
    GET_ALL_CATEGORIES,
    GET_ALL_ZONES,
    GET_ALL_LOCATIONS,
        
    GET_ALL_STATIC,
    GET_ALL_STATIC_WITH_CATEGORIES,
    GET_ALL_STATIC_WITH_ZONES,
    
    GET_LOOT_BY_NAME,
    GET_LOOT_BY_CATEGORY,
    GET_LOOT_BY_ZONE,

    AUTH_TEST,
}