/**
 * @brief Enumeration of different types of REST API requests.
 */
enum RestApiRequestType
{
  GET_ALL_CATEGORIES,             // KRABICE
  GET_ALL_ZONES,                  // KRABICE
  GET_ALL_LOCATIONS,              // KRABICE
  GET_ALL_STATIC,                 // KRABICE
  GET_ALL_STATIC_WITH_CATEGORIES, // KRABICE
  GET_ALL_STATIC_WITH_ZONES,      // KRABICE
  GET_LOOT_BY_NAME,               // KRABICE
  GET_LOOT_BY_CATEGORY,           // KRABICE
  GET_LOOT_BY_ZONE,               // KRABICE
  GET_LOOT_BY_PROXY,              // KRABICE
  GET_RESTART,                    // KRABICE
  AUTH_TEST,                      // AUTH
  GET_TRADER,                     // TRADING
  GET_STOCK,                      // TRADING
  GET_PRODUCT,                    // TRADING
  BUY_PRODUCT,                    // TRADING
  SELL_PRODUCT,                   // TRADING
  GET_PLAYER_DATA,                // WORLD
  UPDATE_PLAYER_DATA,             // WORLD
  GET_PLAYER_CURRENCY,            // WORLD - MONEY
  UPDATE_PLAYER_CURRENCY,         // WORLD - MONEY
  ADD_PLAYER_CURRENCY,            // WORLD - MONEY
  GET_ALL_SPAWNS,                 // SPAWNS
  GET_ALL_RAD_ZONES,              // RADIATION
  IS_IN_RAD_ZONE,                 // RADIATION
  IS_IN_ZONES,                    // NEWLY IMPLEMENTED DUE TO MULTIPLE ZONES
  GET_ALL_RAD_ZONES_COUNT,        // RADIATION
  METRICS_LOOTED_ITEMS_ALL,       // METRICS
  GET_ALL_TRADER_PRICES,          // TRADING
  PENDING_PRODUCT_CREATION,
  ITEM_BASE_CREATE,
  ITEM_BASE_UPDATE,
  ITEM_BASE_DELETE,
  ITEM_BASE_GET,
  ITEM_BASE_GET_ALL,
  GET_ALL_ANOMALY_SPAWNS, // ANOMALY
  GET_SPAWN_ARTIFACT,
  RADIATION_HEATMAP,
  NET_LOGIN,
  NET_LOGOUT,
  NET_REGISTER,
  NET_SEND_MSG,
  NET_GET_NETWORKS,
  NET_GET_PLAYERS,
  NET_AUTH_TO_NETWORK,
  NET_DOWNLOAD_NETWORK_DATA,
  PATH_FIND,
  SPAWN_GET_POINT_ALL,
  SPAWN_GET_POINT_BY_ZONE,
  LAUNCHER_UPDATE_WEAPONS
};
