const string CFG_CRDTN_MAIN_PREFIX          = "<< [CRDTN] >> "; //dontobf
const string CFG_CRDTN_Core_Prefix          = " [CRDTN Core] "; //dontobf
const string CFG_CRDTN_Root_Folder          = "$profile:CRDTN"; //dontobf
const string CFG_CRDTN_ConfigPath           = "$profile:CRDTN\\CRDTN_Core.json"; //dontobf
const string CFG_CRDTN_SpawnPath            = "$profile:CRDTN\\CRDTN_Spawn.json"; //dontobf
const string CFG_CRDTN_LogsFolder           = CFG_CRDTN_Root_Folder + "\\Logs"; //dontobf
const string CFG_CRDTN_NotificationsWrapper = "CRDTN_Core/Layouts/Notifications/notifications.layout"; //dontobf
const string CFG_CRDTN_NotificationsLayout  = "CRDTN_Core/Layouts/Notifications/notification_element.layout"; //dontobf
const string CFG_CRDTN_UI_Menu_Layout          = "CRDTN_Core/Layouts/Menu/CRDTN_Menu.layout"; //dontobf
const string CFG_CRDTN_UI_Menu_ListEntry       = "CRDTN_Core/Layouts/Menu/CRDTN_Menu_ListEntry.layout"; //dontobf
const string CFG_CRDTN_UI_Menu_Category        = "CRDTN_Core/Layouts/Menu/CRDTN_Menu_Category.layout"; //dontobf
const string CFG_CRDTN_UI_Menu_Element_Divider     = "CRDTN_Core/Layouts/Menu/Elements/CRDTN_Body_Divider.layout"; //dontobf
const string CFG_CRDTN_UI_Menu_Element_Header      = "CRDTN_Core/Layouts/Menu/Elements/CRDTN_Body_Header.layout";  //dontobf
const string CFG_CRDTN_UI_Menu_Element_ItemPreview = "CRDTN_Core/Layouts/Menu/Elements/CRDTN_Body_ItemPreview.layout"; //dontobf
const string CFG_CRDTN_UI_Menu_Element_Text        = "CRDTN_Core/Layouts/Menu/Elements/CRDTN_Body_Text.layout"; //dontobf